[ClassVersion("1.0.0"), FriendlyName("cChocoInstaller")] 
class cChocoInstaller : OMI_BaseResource
{
	[Key] string InstallDir;
        [Write] string Version;
        [Write] UInt32 RandomTimeOutBeforeInstallSec;
        [write,EmbeddedInstance("MSFT_Credential")] String Credentials;
        [Write] string Source;
};